# Configure main menu and social menu

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "tryhackme"
name = "TryHackMe"
url = "https://www.tryhackme.com/p/samad1"
weight = -60
[main.params]
icon = "terminal"
newtab = true

#--------------------------------------------------------SOCIALS

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/abdulsamad4"

[social.params]
icon = "brand-linkedin"


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/abdulsamad2002"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto://blackhawkalpha009@gmail.com"

[social.params]
icon = "mail"


[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"